export const rabbitRecipient = {
  HASH_PASSWORD: 'HASH_PASSWORD',
  GENERATED_TOKENS: 'GENERATED_TOKENS',
  COMPARISON_PASSWORD: 'COMPARISON_PASSWORD',
  VERIFY_REFRESH_TOKEN: 'VERIFY_REFRESH_TOKEN',
};
