// rabbit provider

export const COMPUTING_RABBIT_PROVIDER = 'COMPUTING_RABBIT_PROVIDER';

export const rabbitSender = {
  HASH_PASSWORD: 'HASH_PASSWORD',
  COMPARISON_PASSWORD: 'COMPARISON_PASSWORD',
  GENERATED_TOKENS: 'GENERATED_TOKENS',
  VERIFY_REFRESH_TOKEN: 'VERIFY_REFRESH_TOKEN',
};
